{
 "title": "Crypto tracker",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BTC/USDT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "coinstats_btc_price" }
   ]
  },
  {
   "title": "BTC/USDT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "coinstats_btc_price" }
   ]
  },
  {
   "title": "CRO/USDT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "coinstats_cro_price{}" }
   ]
  },
  {
   "title": "BNB/USDT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "coinstats_bnb_price{}" }
   ]
  }
 ]
}