{
 "title": "Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GO Heap Alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes) by(instance)"
    }
   ]
  },
  {
   "title": "Go Threads Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(go_threads[$__rate_interval])) by(instance)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_requests_total[$__rate_interval])) by (code) "
    }
   ]
  }
 ]
}