apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service:9090
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST